name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_63-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs_on: ${{ matrix.os }}
    steps:
      - uses: actions/chechout@v4
      - name: Install tools
        run: sudo apt-get update --yes && sudo apt-get install --yes libxi-dev libx11-dev libxcb1 libxrandr2 libdbus-1-3 libxtst-dev
        if: contains(matrix.osm 'ubuntu')
      - uses: taiki-e/upload-rust-binary-actions@v1
        with:
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}